'use strict';

const fs = require('fs');
const path = require('path');

const readerJs = fs.readFileSync(path.join(__dirname, '..', 'src', 'reader', 'reader.js'), 'utf8');
const readerCss = fs.readFileSync(path.join(__dirname, '..', 'src', 'reader', 'reader.css'), 'utf8');

// Escape backticks, backslashes, and dollar signs for template literal embedding
function escapeForTemplate(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
}

const output = `'use strict';

// Embedded reader assets for monolithic builds.
// Generated by scripts/embedAssets.js — do not edit by hand.
// To regenerate: node scripts/embedAssets.js

const READER_JS = \x60${escapeForTemplate(readerJs)}\x60;

const READER_CSS = \x60${escapeForTemplate(readerCss)}\x60;

module.exports = { READER_JS, READER_CSS };
`;

const outPath = path.join(__dirname, '..', 'src', 'generator', 'embeddedAssets.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log(`OK: ${outPath} (reader.js: ${readerJs.length} chars, reader.css: ${readerCss.length} chars)`);
