'use strict';

// Embedded reader assets for monolithic builds.
// Generated by scripts/embedAssets.js — do not edit by hand.
// To regenerate: node scripts/embedAssets.js

const READER_JS = `(function () {
  'use strict';

  const THEME_KEY = 'epub-theme';
  const FONT_KEY = 'epub-font-size';
  const ENRICHED_KEY = 'epub-css-enriched';
  const POS_PREFIX = 'epub-pos:';
  const FONT_MIN = 0.8;
  const FONT_MAX = 1.8;
  const FONT_STEP = 0.1;

  // ---- State from page ----
  const chapterIndex = parseInt(document.body.getAttribute('data-chapter-index'), 10);
  const totalChapters = parseInt(document.body.getAttribute('data-chapter-total'), 10) || 1;
  const pathPrefix = window.TOC_PATH_PREFIX || '';
  const toc = window.TOC || {};
  const tocItems = toc.tree || toc.chapters || [];

  // ---- Theme ----
  function applyTheme(theme) {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem(THEME_KEY, theme);
  }

  (function initTheme() {
    applyTheme(localStorage.getItem(THEME_KEY) || 'light');
  }());

  document.getElementById('toggle-theme').addEventListener('click', () => {
    applyTheme(document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
  });

  // ---- Font size ----
  function applyFontSize(size) {
    const clamped = Math.min(FONT_MAX, Math.max(FONT_MIN, size));
    document.documentElement.style.setProperty('--font-size', clamped + 'rem');
    localStorage.setItem(FONT_KEY, String(clamped));
    return clamped;
  }

  (function initFontSize() {
    const saved = parseFloat(localStorage.getItem(FONT_KEY));
    applyFontSize(isNaN(saved) ? 1.1 : saved);
  }());

  document.getElementById('font-up').addEventListener('click', () => {
    const cur = parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--font-size')) || 1.1;
    applyFontSize(cur + FONT_STEP);
  });

  document.getElementById('font-down').addEventListener('click', () => {
    const cur = parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--font-size')) || 1.1;
    applyFontSize(cur - FONT_STEP);
  });

  // ---- TOC sidebar: hierarchical tree ----
  function buildSidebar() {
    const sidebar = document.getElementById('toc-sidebar');
    if (!sidebar) return;

    // Title
    const titleEl = document.createElement('div');
    titleEl.className = 'sidebar-title';
    titleEl.textContent = toc.title || 'Indice';
    sidebar.appendChild(titleEl);

    if (!tocItems.length) return;

    // Pre-compute which items have children
    const hasChildren = tocItems.map((item, i) => {
      const itemLevel = item.level || 0;
      for (let j = i + 1; j < tocItems.length; j++) {
        const nextLevel = tocItems[j].level || 0;
        if (nextLevel <= itemLevel) break;
        if (nextLevel > itemLevel) return true;
      }
      return false;
    });

    // Build nested UL using a stack
    const root = document.createElement('ul');
    root.className = 'toc-list';

    // stack entries: { ul, level }
    const stack = [{ ul: root, level: -1 }];

    tocItems.forEach((item, i) => {
      const itemLevel = item.level || 0;

      // Pop until parent level < current item level
      while (stack.length > 1 && stack[stack.length - 1].level >= itemLevel) {
        stack.pop();
      }
      const parentUl = stack[stack.length - 1].ul;

      const li = document.createElement('li');
      const row = document.createElement('div');
      row.className = 'toc-row';

      // Toggle button (only for items with children)
      let childUl = null;
      if (hasChildren[i]) {
        const toggle = document.createElement('button');
        toggle.className = 'toc-toggle';
        toggle.innerHTML = '&#9654;'; // ▶
        toggle.setAttribute('aria-expanded', 'false');
        row.appendChild(toggle);

        childUl = document.createElement('ul');
        childUl.className = 'toc-children hidden';

        toggle.addEventListener('click', function (e) {
          e.preventDefault();
          e.stopPropagation();
          const isHidden = childUl.classList.contains('hidden');
          childUl.classList.toggle('hidden', !isHidden);
          toggle.innerHTML = isHidden ? '&#9660;' : '&#9654;'; // ▼ / ▶
          toggle.setAttribute('aria-expanded', String(isHidden));
        });
      }

      // Link
      const a = document.createElement('a');
      const href = item.href || '#';
      a.href = href.startsWith('http') ? href : pathPrefix + href;
      a.textContent = item.title || '';
      a.title = item.title || '';
      row.appendChild(a);
      li.appendChild(row);

      // Mark current chapter
      const itemChapterIdx = item.chapterIndex !== undefined ? item.chapterIndex : item.index;
      if (itemChapterIdx === chapterIndex) {
        li.classList.add('current');
      }

      parentUl.appendChild(li);

      if (childUl) {
        li.appendChild(childUl);
        stack.push({ ul: childUl, level: itemLevel });
      }
    });

    sidebar.appendChild(root);

    // Auto-expand ancestors of current chapter and scroll into view
    const currentLi = root.querySelector('li.current');
    if (currentLi) {
      let node = currentLi.parentElement;
      while (node && node !== sidebar) {
        if (node.classList.contains('toc-children')) {
          node.classList.remove('hidden');
          const parentLi = node.parentElement;
          if (parentLi) {
            const toggle = parentLi.querySelector(':scope > .toc-row > .toc-toggle');
            if (toggle) {
              toggle.innerHTML = '&#9660;';
              toggle.setAttribute('aria-expanded', 'true');
            }
          }
        }
        node = node.parentElement;
      }
      setTimeout(() => currentLi.scrollIntoView({ block: 'nearest' }), 50);
    }
  }

  // ---- Sidebar toggle ----
  const sidebar = document.getElementById('toc-sidebar');
  const SIDEBAR_WIDTH_KEY = 'epub-sidebar-width';

  (function initSidebar() {
    // Restore saved width
    const savedWidth = parseInt(localStorage.getItem(SIDEBAR_WIDTH_KEY), 10);
    if (savedWidth && savedWidth >= 180 && savedWidth <= 450) {
      sidebar.style.width = savedWidth + 'px';
    }
    
    if (window.innerWidth <= 768) sidebar.classList.add('hidden');
  }());

  document.getElementById('toggle-toc').addEventListener('click', () => {
    sidebar.classList.toggle('hidden');
  });

  // ---- Sidebar resize ----
  (function initResize() {
    const resizeHandle = document.createElement('div');
    resizeHandle.className = 'sidebar-resize';
    resizeHandle.setAttribute('title', 'Trascina per ridimensionare');
    sidebar.appendChild(resizeHandle);

    let isDragging = false;
    let startX, startWidth;

    resizeHandle.addEventListener('mousedown', (e) => {
      isDragging = true;
      startX = e.clientX;
      startWidth = sidebar.offsetWidth;
      resizeHandle.classList.add('dragging');
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
      e.preventDefault();
    });

    document.addEventListener('mousemove', (e) => {
      if (!isDragging) return;
      const dx = e.clientX - startX;
      const newWidth = Math.min(450, Math.max(180, startWidth + dx));
      sidebar.style.width = newWidth + 'px';
    });

    document.addEventListener('mouseup', () => {
      if (isDragging) {
        isDragging = false;
        resizeHandle.classList.remove('dragging');
        document.body.style.cursor = '';
        document.body.style.userSelect = '';
        // Save width to localStorage
        localStorage.setItem(SIDEBAR_WIDTH_KEY, sidebar.offsetWidth);
      }
    });
  }());

  sidebar.addEventListener('click', (e) => {
    if (e.target.tagName === 'A' && window.innerWidth <= 768) {
      sidebar.classList.add('hidden');
    }
  });

  // ---- Progress bar ---- */
  (function updateProgress() {
    const fill = document.querySelector('.progress-fill');
    if (!fill || chapterIndex < 0) return;
    fill.style.width = (totalChapters > 1 ? (chapterIndex + 1) / totalChapters * 100 : 100) + '%';
  }());

  // ---- Scroll position persistence ----
  if (chapterIndex >= 0) {
    const posKey = POS_PREFIX + chapterIndex;

    window.addEventListener('scroll', () => {
      localStorage.setItem(posKey, String(window.scrollY));
    }, { passive: true });

    window.addEventListener('load', () => {
      const navType = performance.getEntriesByType('navigation')[0]?.type;
      if (navType === 'navigate') return;
      const saved = parseInt(localStorage.getItem(posKey), 10);
      if (!isNaN(saved) && saved > 0) setTimeout(() => window.scrollTo(0, saved), 80);
    });
  }

  // ---- Enriched CSS toggle ----
  (function initEnriched() {
    const href = document.body.dataset.enrichedCssHref;
    const btn = document.getElementById('toggle-enriched');
    if (!href || !btn) return;

    btn.style.display = '';

    function applyEnriched(enabled) {
      let link = document.getElementById('epub-enriched-css');
      if (enabled && !link) {
        link = document.createElement('link');
        link.rel = 'stylesheet';
        link.id = 'epub-enriched-css';
        link.href = href;
        document.head.appendChild(link);
      } else if (!enabled && link) {
        link.remove();
      }
      btn.classList.toggle('active', enabled);
      localStorage.setItem(ENRICHED_KEY, String(enabled));
    }

    applyEnriched(localStorage.getItem(ENRICHED_KEY) === 'true');

    btn.addEventListener('click', () => {
      applyEnriched(!document.getElementById('epub-enriched-css'));
    });
  }());

  // ---- Init ----
  buildSidebar();
}());
`;

const READER_CSS = `/* ---- CSS custom properties (light theme default) ---- */
:root {
  --font-size: 1.1rem;
  --font-family: Georgia, 'Times New Roman', serif;
  --line-height: 1.8;
  --max-width: 700px;
  --header-h: 48px;

  --color-bg: #fdf6e3;
  --color-text: #2c2c2c;
  --color-muted: #888;
  --color-accent: #c0392b;
  --color-header-bg: #fff;
  --color-header-border: #e0e0e0;
  --color-sidebar-bg: #f5f0e8;
  --color-sidebar-border: #ddd;
  --color-border: #e0e0e0;
  --color-hover: #f0ebe0;
  --color-progress: #c0392b;
  --color-nav-bg: #f5f0e8;
  --shadow-sidebar: 2px 0 8px rgba(0,0,0,.07);
}

[data-theme="dark"] {
  --color-bg: #1a1a2e;
  --color-text: #e0e0e0;
  --color-muted: #888;
  --color-accent: #e74c3c;
  --color-header-bg: #16213e;
  --color-header-border: #2d2d4e;
  --color-sidebar-bg: #16213e;
  --color-sidebar-border: #2d2d4e;
  --color-border: #2d2d4e;
  --color-hover: #1e2a4a;
  --color-progress: #e74c3c;
  --color-nav-bg: #16213e;
  --shadow-sidebar: 2px 0 8px rgba(0,0,0,.3);
}

/* ---- Anchor offset for sticky header ---- */
[id] {
  scroll-margin-top: calc(var(--header-h) + 0.5rem);
}

/* ---- Reset & base ---- */
*, *::before, *::after { box-sizing: border-box; }

html, body {
  margin: 0;
  padding: 0;
  background: var(--color-bg);
  color: var(--color-text);
  font-family: var(--font-family);
  font-size: var(--font-size);
  line-height: var(--line-height);
  transition: background .2s, color .2s;
}

/* ---- Header ---- */
.reader-header {
  position: sticky;
  top: 0;
  z-index: 200;
  display: flex;
  align-items: center;
  gap: .8rem;
  padding: .5rem 1rem;
  height: var(--header-h);
  background: var(--color-header-bg);
  border-bottom: 1px solid var(--color-header-border);
  box-shadow: 0 1px 4px rgba(0,0,0,.06);
}

.book-title {
  flex: 1;
  font-size: .9rem;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  color: var(--color-muted);
}

.controls {
  display: flex;
  gap: .4rem;
}

.reader-header button,
.controls button {
  padding: .3rem .6rem;
  background: transparent;
  border: 1px solid var(--color-border);
  border-radius: 4px;
  cursor: pointer;
  color: var(--color-text);
  font-size: .85rem;
  font-family: inherit;
  transition: background .15s;
}

.reader-header button:hover,
.controls button:hover {
  background: var(--color-hover);
}

.controls button.active {
  background: var(--color-accent);
  color: #fff;
  border-color: var(--color-accent);
}

.controls button.active:hover {
  opacity: .85;
  background: var(--color-accent);
}

/* ---- Progress bar ---- */
.progress-bar {
  height: 3px;
  background: var(--color-border);
}

.progress-fill {
  height: 100%;
  background: var(--color-progress);
  transition: width .3s;
}

/* ---- Layout: sidebar + content ---- */
.reader-layout {
  display: flex;
  align-items: flex-start;   /* needed for sticky sidebar */
}

/* ---- Sidebar (sticky) ---- */
.sidebar {
  width: 260px;
  min-width: 180px;
  max-width: 450px;
  flex-shrink: 0;
  background: var(--color-sidebar-bg);
  border-right: 1px solid var(--color-sidebar-border);
  box-shadow: var(--shadow-sidebar);
  overflow-y: auto;
  overflow-x: hidden;
  padding: .75rem 0;

  /* Sticky: stays in view while chapter content scrolls */
  position: sticky;
  top: var(--header-h);
  height: calc(100vh - var(--header-h));
  opacity: 1;
  transition: width .25s ease, padding .25s ease, opacity .2s ease;
}

.sidebar.hidden {
  width: 0 !important;
  min-width: 0 !important;
  max-width: 0 !important;
  padding: 0 !important;
  overflow: hidden;
  border-right: none;
  opacity: 0;
  pointer-events: none;
}

/* ---- Resize handle ---- */
.sidebar-resize {
  position: absolute;
  top: 0;
  right: 0;
  width: 6px;
  height: 100%;
  cursor: col-resize;
  background: transparent;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10;
  opacity: 1;
  transition: opacity .15s;
}

.sidebar.hidden .sidebar-resize {
  display: none;
}

.sidebar-resize::before {
  content: '';
  width: 2px;
  height: 40px;
  background: var(--color-sidebar-border);
  border-radius: 1px;
  opacity: 0.5;
  transition: opacity .15s;
}

.sidebar-resize:hover::before,
.sidebar-resize.dragging::before {
  opacity: 1;
  background: var(--color-accent);
}

.sidebar-title {
  font-size: .75rem;
  text-transform: uppercase;
  letter-spacing: .08em;
  color: var(--color-muted);
  padding: 0 .75rem .5rem;
  margin: 0 0 .25rem;
  border-bottom: 1px solid var(--color-border);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  white-space: nowrap;
  overflow: hidden;
}

/* ---- TOC tree ---- */
.toc-list,
.toc-children {
  list-style: none;
  margin: 0;
  padding: 0;
}

.toc-children {
  padding-left: .75rem;
  border-left: 1px dashed var(--color-border);
  margin-left: 1.1rem;
}

.toc-children.hidden {
  display: none;
}

.toc-list li {
  display: flex;
  flex-direction: column;
}

.toc-list li .toc-row {
  display: flex;
  align-items: center;
}

.toc-toggle {
  flex-shrink: 0;
  width: 20px;
  height: 20px;
  padding: 0;
  margin: .15rem .1rem .15rem .4rem;
  background: transparent;
  border: none;
  cursor: pointer;
  color: var(--color-muted);
  font-size: .65rem;
  line-height: 1;
  border-radius: 3px;
  transition: background .15s, color .15s;
  display: flex;
  align-items: center;
  justify-content: center;
}

.toc-toggle:hover {
  background: var(--color-hover);
  color: var(--color-text);
}

.toc-list li a {
  flex: 1;
  min-width: 0;
  display: block;
  padding: .35rem .6rem .35rem .25rem;
  font-size: .83rem;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  color: var(--color-text);
  text-decoration: none;
  border-left: 2px solid transparent;
  overflow-wrap: break-word;
  word-break: break-word;
  hyphens: auto;
  transition: background .12s, color .12s;
}

.toc-list li a:hover {
  background: var(--color-hover);
  color: var(--color-text);
}

.toc-list li.current > .toc-row > a {
  border-left-color: var(--color-accent);
  color: var(--color-accent);
  font-weight: 600;
}

/* Indent level-0 items have slightly more padding */
.toc-list > li > .toc-row > a {
  padding-left: .75rem;
  border-left-width: 3px;
}

/* ---- Chapter content ---- */
.chapter-content {
  flex: 1;
  min-width: 300px;
  padding: 2.5rem 2rem;
  max-width: 100%;
  margin: 0 auto;
  width: 100%;
}

.chapter-content h1,
.chapter-content h2,
.chapter-content h3,
.chapter-content h4 {
  line-height: 1.3;
  margin: 2rem 0 .8rem;
  color: var(--color-text);
}

.chapter-content h1 { font-size: 1.8em; }
.chapter-content h2 { font-size: 1.4em; }
.chapter-content h3 { font-size: 1.15em; }

.chapter-content p {
  margin: 0 0 1.1em;
  text-align: justify;
  hyphens: auto;
}

.chapter-content img {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 1.5rem auto;
  border-radius: 4px;
}

.chapter-content blockquote {
  border-left: 4px solid var(--color-accent);
  margin: 1.5rem 0;
  padding: .5rem 1.5rem;
  color: var(--color-muted);
  font-style: italic;
}

.chapter-content a {
  color: var(--color-accent);
}

.chapter-content code,
.chapter-content pre {
  font-family: 'Courier New', Courier, monospace;
  font-size: .9em;
  background: var(--color-hover);
  padding: .1em .3em;
  border-radius: 3px;
}

.chapter-content pre code {
  display: block;
  padding: 1rem;
  overflow-x: auto;
}

/* ---- Chapter navigation ---- */
.chapter-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.5rem 2rem;
  border-top: 1px solid var(--color-border);
  background: var(--color-nav-bg);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.chapter-nav a {
  color: var(--color-accent);
  text-decoration: none;
  font-weight: 600;
  padding: .5rem .9rem;
  border: 1px solid var(--color-accent);
  border-radius: 4px;
  transition: background .15s, color .15s;
}

.chapter-nav a:hover {
  background: var(--color-accent);
  color: #fff;
}

.nav-disabled {
  display: inline-block;
  width: 1px;
}

/* ---- Responsive ---- */
@media (max-width: 768px) {
  .sidebar {
    position: fixed;
    top: var(--header-h);
    left: 0;
    z-index: 300;
    width: 80vw !important;
    max-width: 300px;
  }

  .sidebar.hidden {
    transform: translateX(-100%);
    width: 80vw !important;
  }

  .chapter-content {
    padding: 1.5rem 1rem;
  }
}
`;

module.exports = { READER_JS, READER_CSS };
